### PR TITLE
Only highlight "supported" languages and fix typescript details hl

### LINKED ISSUE #2: Only try to highlight supported languages
Hi :) 

This looks very cool and promising! I was looking a bit through this, and noticed the `M.default_highlight`. I was kind of hoping that this plugin only would try to highlight the languages that is supported, and just do nothing for the other languages. So I was thinking about if you are open to just simply remove that else-statement and that method/config option?

Another thing:

Is there any need for the `M.apply_post_processing` when lspkind which is referred to in the README can do the same?😅 Less code to maintain😄

While I am at it, I noticed that in typescript the detail tag is not highlighted with `@comment` as the other languages were (it also seems to be highlighted with a comment color in zed).

I am open to creating a PR for all of these things if you want, or just the things you feel comfortable with changing😄

### PR DESCRIPTION
**Pull request by seblj**
So this is my proposal and will close #2 

I see that you found a way to use blink.cmp with this and lspkind is only for `cmp` at least for now, so I agree we can just leave the trimming of the line.

My proposal is to just do nothing except for the post processing if the language is not "supported"

### CODE REVIEW

File: lua/colorful-menu/init.lua [hunk 1]
```diff
@@ -170,14 +171,6 @@ function M.rust_compute_completion_highlights(completion_item, ft)
 	return vim_item
 end
 
-function M.defaut_highlight(completion_item, ft)
```
Comment (xzbdmw) [inline lua/colorful-menu/init.lua:173]: How about add an option `config.ft.fallback`, default to true to call this function, if not, we will return nil to let user decide.

File: lua/colorful-menu/init.lua [hunk 2]
```diff
@@ -126,7 +127,7 @@ function M.highlights(completion_item, ft)
 			return
 		end
 	else
-		item = M.defaut_highlight(completion_item, ft)
+		item = { text = completion_item.label }
```
Comment (xzbdmw) [inline lua/colorful-menu/init.lua:130]: Let's return nil, so user can decide what to show.

**Review by xzbdmw — COMMENTED** [review]
Thank you! Leave some comments.

File: lua/colorful-menu/init.lua (hunk 1 above)
Comment (seblj) [reply lua/colorful-menu/init.lua:173]: Sure

File: lua/colorful-menu/init.lua (hunk 2 above)
Comment (seblj) [reply lua/colorful-menu/init.lua:130]: But then post processing will not be done... It feels a bit weird to do trimming for this, but also have to do trimming for the languages that are not supported. In that case, I think it would be even better to just remove post-processing and the trimming all together and leave that up to either lspkind and/or blink.cmp which seems to have it as an option itself judging from reading the snippet in the README

Comment (xzbdmw) [reply lua/colorful-menu/init.lua:130]: Understandable, but I'm afraid someone who don't use lspkind, and in the past never bothered by a very long line, will be surprised by long signatures here.

I agree that's a bit strange to do the same thing, so let's make `config.max_width` default to be nil, and let user to overwrite it

Comment (seblj) [reply lua/colorful-menu/init.lua:130]: But it will still be the same problem having to set maxwidth two places even if we change the default. We can just return nil and then the user must set maxwidth both in this plugin and lspkind if they are using that then?

Comment (xzbdmw) [reply lua/colorful-menu/init.lua:130]: Yes. If they used to not care about width, then it is the same as before.

Comment (seblj) [reply lua/colorful-menu/init.lua]: I changed it to just return nil, but I didn't change the default width. Is that okay?

Comment (seblj) [reply lua/colorful-menu/init.lua]: I can add an option if it should default highlight or not though as you wanted

File: lua/colorful-menu/init.lua [hunk 3]
```diff
@@ -170,7 +177,7 @@ function M.rust_compute_completion_highlights(completion_item, ft)
 	return vim_item
 end
 
-function M.defaut_highlight(completion_item, ft)
+function M.default_highlight(completion_item, ft)
```
Comment (seblj) [inline lua/colorful-menu/init.lua:180]: I just changed the name of this to not have a typo while I was at it

**Review by seblj — COMMENTED** [review]
Is something like this what you were thinking?

**Comment by xzbdmw** [comment]
Thank you!
